### ISSUE TITLE
.getScore() tests

### ISSUE THREAD

**Issue by Fubinator** [turingsecure/cvss.js#15]
We need extensive testing for the `getScore()` function. A good place to get vectors and their calculations is: https://www.first.org/cvss/calculator/3.0

**Comment by dandelionsam** [comment]
I can handle this. Would you assign this issue to me? :)

**Comment by Fubinator** [comment]
Yes sure go for it @dandelionsam! If you have any questions feel free to ask.

**Comment by dandelionsam** [comment]
Hello, I didn't know CVSS, so I gave a quick read at the docs, then I read the code. For the testing purpose, in order to calculate the score, I'm thinking about a vector generator, which seems to be in the website, although isn't working at all. But to calculate vector score I will need to use the `getScore()` function, so it seems a recursive problem. Any idea to avoid this?
